export const categories = {
    New: ["AsmrEarCleaning", "AsmrStickySlime", "AsmrEarBrushing", "AsmrFallingBeads", "AsmrDriedHerbs", "AsmrSlime", "AsmrBubbleWrap", "AsmrEarBlowing", "AsmrEarMassage", "AsmrMicScratching"],
    // AllTag: ["Birds", "River", "Rain", "Ocean", "Night", "AsmrVinylCrackle", "Flute", "Winds", "WhiteNoise", "Eternity", "MusicBox", "Lounge", "Shower", "Piano", "Orchestral", "Waterfall", "Thunder", "SpokenBreathing", "AsmrBedSheets", "BrainScanner", "Zen", "Campfire", "Melody", "CanadianForest", "Lakeshore", "WalkingInWoods", "AsmrSlime", "AsmrStickySlime", "Bumblebees", "Chicks", "Chickens", "Cows", "Dolphins", "Ducks", "HorsesTrotting", "MorningBirdsong", "SheepWalking", "TropicalBirds", "AirConditioner", "Dishwasher", "AsmrPageTurning", "CoffeeShop", "Autumn", "UprightPiano", "BrownNoise", "PinkNoise", "AsmrFizzyDrink", "LaserBeam", "ComputerBeeps", "OuterSpace", "RocketEngine", "WalkingInSpaceship", "HeartBeat", "Astral", "Fountain", "Train", "AsmrFoam", "Tribal", "India", "UrbanRain", "Cavern", "Reactor", "WindChimes", "Spaceship", "AsmrMakeupBrush", "Sailing", "Voices", "Watching", "BassMusic", "SpokenSleepAffirmations", "ColdRattle", "AsmrElvishWhispers", "Chirp", "Orbit", "Drum", "ServerRoom", "Storm", "AsmrBoilingWater", "Flute2", "Choir", "Airplane", "Starfield", "SunnyDay", "Guitar", "AsmrWriting", "Dramatic", "Butterfly", "Medieval", "EarthDrama", "Dreams", "AsmrIceCube", "WindSurge", "Forest", "Abstract", "BabyShusher", "GreenNoise", "MilkyWay", "AsmrEarMassage", "AsmrEarBlowing", "Spring", "AsmrFingerFlutter", "Toskana", "City", "Sprinkler", "SlowWaves", "LightRain", "AsmrSkillet", "HeavyRain", "RainyDay", "AsmrBubbleWrap", "Underwater", "TibetanBowlSmall", "TibetanBowlMedium", "TibetanBowlBig", "AsmrPurring", "Immersed", "Afternoon", "Rainstorm", "ForestRain", "Whales", "Seaside", "IcySnow", "AsmrDriedHerbs", "CuckooBird", "Aquarium", "BambooWaterFountain", "BathFilling", "AsmrMicScratching", "BoilingPotion", "DrivingInRain", "FloatingBoat", "HotTub", "RainOnWindow", "WavesOnRocks", "Whales2", "Seagulls", "RainOnRoof", "Duduk", "Playground", "AsmrRainDrops", "Owls", "Humming", "GrandfatherClock", "Frogs", "Dryer", "CatPurring", "BaliMist", "Thunderstorm", "CityAmbience", "IndianDrums", "PachelbelCanon", "Wolf", "FogHorn", "Vacuum", "Loon", "Keyboard", "MonkChant", "AsmrWalkingOnSnow", "OscillatingFan", "Womb", "BabyMarimba", "SpokenHypnoticWords", "BabyBells", "SingingBowlSmall", "SingingBowlMedium", "SingingBowlBig", "Jupiter", "Cicadas", "WindInTrees", "Peepers", "AsmrEarBrushing", "RustlingLeaves", "Crowd", "RainOnTent", "TibetanBowls", "BrahmsLullaby", "SpokenCountingSheep", "Joy", "Rattle", "LappingWater", "AsmrFallingBeads", "DistantTrain", "MagicChimes", "Carnival", "TruckEngine", "SweetDreams", "AsmrEarCleaning", "HairDryer", "SweetHourPrayer", "Ancestral", "FireCrackles", "Highway", "Om", "Harmony", "Binaural2.5hz", "Binaural4hz", "Binaural5hz", "Binaural8hz", "Binaural10hz", "Binaural20hz", "Isochronic2.5hz", "Isochronic4hz", "Isochronic5hz", "Isochronic8hz", "Isochronic10hz", "Isochronic20hz", "Solfeggio174hz", "Solfeggio285hz", "Solfeggio396hz", "Solfeggio417hz", "Solfeggio432hz", "Solfeggio528hz"],
    Spoken: ["SpokenBreathing", "SpokenSleepAffirmations", "SpokenHypnoticWords", "SpokenCountingSheep"],
    Water: ["River", "Ocean", "Rain", "Waterfall", "UrbanRain", "Cavern", "SlowWaves", "HeavyRain", "RainyDay", "Underwater", "Rainstorm", "RainOnRoof", "IcySnow", "Aquarium", "BambooWaterFountain", "BathFilling", "BoilingPotion", "DrivingInRain", "FloatingBoat", "HotTub", "RainOnWindow", "WavesOnRocks", "Immersed", "Seaside", "LappingWater", "Fountain", "Sailing", "LightRain", "ForestRain", "Lakeshore", "RainOnTent", "Shower", "Dishwasher"],
    Nature: ["Winds", "Thunder", "Campfire", "Night", "Storm", "Toskana", "CanadianForest", "WalkingInWoods", "Afternoon", "Thunderstorm", "Jupiter", "WindInTrees", "FireCrackles", "HeartBeat", "SunnyDay", "WindSurge", "Forest", "RustlingLeaves"],
    City: ["UrbanRain", "RainOnRoof", "GrandfatherClock", "CityAmbience", "OscillatingFan", "Vacuum", "Crowd", "Highway", "Train", "DistantTrain", "ColdRattle", "Aquarium", "BathFilling", "DrivingInRain", "HotTub", "Sprinkler", "Playground", "Dryer", "FogHorn", "Keyboard", "Carnival", "TruckEngine", "HairDryer", "Shower", "AirConditioner", "Dishwasher", "CoffeeShop"],
    Melodies: ["Flute", "Lounge", "Piano", "Orchestral", "Zen", "Melody", "WindChimes", "Butterfly", "Medieval", "Humming", "Duduk", "MonkChant", "Eternity", "Astral", "Tribal", "India", "Voices", "Watching", "BassMusic", "Drum", "Flute2", "Choir", "Guitar", "Dramatic", "EarthDrama", "Dreams", "Abstract", "Spring", "City", "BaliMist", "IndianDrums", "PachelbelCanon", "MagicChimes", "SweetHourPrayer", "Ancestral", "Harmony", "Om", "TibetanBowlSmall", "TibetanBowlMedium", "TibetanBowlBig", "SingingBowl", "SingingBowlMedium", "SingingBowlBig", "Joy", "MilkyWay", "Orbit", "Starfield", "Autumn", "UprightPiano"],
    Animal: ["Bumblebees", "Chicks", "Chickens", "Cows", "Dolphins", "Ducks", "HorsesTrotting", "MorningBirdsong", "SheepWalking", "TropicalBirds", "Birds", "Frogs", "CatPurring", "CuckooBird", "Peepers", "Chirp", "Whales2", "Whales", "Seagulls", "Owls", "Wolf", "Loon", "Cicadas"],
    ASMR: ["AsmrVinylCrackle", "AsmrBedSheets", "AsmrPageTurning", "AsmrFizzyDrink", "AsmrFoam", "AsmrMakeupBrush", "AsmrElvishWhispers", "AsmrBoilingWater", "AsmrWriting", "AsmrIceCube", "AsmrFingerFlutter", "AsmrSkillet", "AsmrPurring", "AsmrRainDrops", "AsmrEarCleaning", "AsmrStickySlime", "AsmrEarBrushing", "AsmrFallingBeads", "AsmrDriedHerbs", "AsmrSlime", "AsmrBubbleWrap", "AsmrEarBlowing", "AsmrEarMassage", "AsmrMicScratching", "AsmrWalkingOnSnow"],
    Noise: ["WhiteNoise", "BrownNoise", "PinkNoise", "Spaceship", "Airplane", "GreenNoise", "AirConditioner"],
    Baby: ["Humming", "BrahmsLullaby", "MusicBox", "Womb", "SweetDreams", "BabyBells", "BabyShusher", "BabyMarimba", "Rattle"],
    SciFi: ["BrainScanner", "ComputerBeeps", "OuterSpace", "RocketEngine", "WalkingInSpaceship", "LaserBeam", "Reactor", "Jupiter", "Spaceship", "ServerRoom"],
    Brainwave: ["Isochronic10hz", "Isochronic20hz", "Isochronic2.5hz", "Isochronic4hz", "Isochronic5hz", "Isochronic8hz", "Binaural10hz", "Binaural20hz", "Binaural2.5hz", "Binaural4hz", "Binaural5hz", "Binaural8hz", "Solfeggio174hz", "Solfeggio285hz", "Solfeggio396hz", "Solfeggio417hz", "Solfeggio432hz", "Solfeggio528hz"]
} as any
export const audioBaseUrl = 'https://full-audio-resource-1256270265.cos.ap-shanghai.myqcloud.com/'
export const CN = {
    //tag
    'tag.New': '最新',
    'tag.Spoken': '讲述',
    'tag.Water': '水',
    'tag.Nature': '自然',
    'tag.City': '城市',
    'tag.Melodies': '旋律',
    'tag.Animal': '动物',
    'tag.ASMR': 'ASMR',
    'tag.Noise': '白噪音',
    'tag.Baby': '婴儿',
    'tag.SciFi': '科幻',
    'tag.Brainwave': '脑波',
    //music
    'audio.AsmrEarCleaning': '清洁耳朵',
    'audio.AsmrStickySlime': '黏滑史莱姆',
    'audio.AsmrEarBrushing': '耳朵按摩',
    'audio.AsmrFallingBeads': '掉落的珠串',
    'audio.AsmrDriedHerbs': '干燥的药草',
    'audio.AsmrSlime': '史莱姆',
    'audio.AsmrBubbleWrap': '泡泡包装纸',
    'audio.AsmrEarBlowing': '耳朵吹气',
    'audio.AsmrEarMassage': '耳朵按摩',
    'audio.AsmrMicScratching': '抓挠',
    'audio.Birds': '鸟',
    'audio.River': '河流',
    'audio.Rain': '下雨',
    'audio.Ocean': '海洋',
    'audio.Night': '夜晚',
    'audio.AsmrVinylCrackle': '划塑料声',
    'audio.Flute': '长笛',
    'audio.Winds': '风',
    'audio.WhiteNoise': '白噪音',
    'audio.Eternity': '永恒',
    'audio.MusicBox': '音乐盒',
    'audio.Lounge': '休息室',
    'audio.Shower': '淋浴',
    'audio.Piano': '钢琴',
    'audio.Orchestral': '管弦乐',
    'audio.Waterfall': '瀑布',
    'audio.Thunder': '雷',
    'audio.SpokenBreathing': '呼吸',
    'audio.AsmrBedSheets': '床单',
    'audio.BrainScanner': '大脑扫描仪',
    'audio.Zen': '禅',
    'audio.Campfire': '营火',
    'audio.Melody': '旋律',
    'audio.CanadianForest': '加拿大森林',
    'audio.Lakeshore': '湖岸',
    'audio.WalkingInWoods': '林间散步',
    'audio.Bumblebees': '大黄蜂',
    'audio.Chicks': '小鸡',
    'audio.Chickens': '鸡',
    'audio.Cows': '牛',
    'audio.Dolphins': '海豚',
    'audio.Ducks': '鸭',
    'audio.HorsesTrotting': '马蹄声',
    'audio.MorningBirdsong': '清晨鸟鸣',
    'audio.SheepWalking': '绵羊步行',
    'audio.TropicalBirds': '热带鸟',
    'audio.AirConditioner': '空调',
    'audio.Dishwasher': '洗碗机',
    'audio.AsmrPageTurning': '翻页',
    'audio.CoffeeShop': '咖啡馆',
    'audio.Autumn': '秋天',
    'audio.UprightPiano': '立式钢琴',
    'audio.BrownNoise': '棕噪声',
    'audio.PinkNoise': '粉红噪声',
    'audio.AsmrFizzyDrink': '碳酸饮料',
    'audio.LaserBeam': '激光束',
    'audio.ComputerBeeps': '电脑哔哔声',
    'audio.OuterSpace': '外太空',
    'audio.RocketEngine': '火箭引擎',
    'audio.WalkingInSpaceship': '飞船行走',
    'audio.HeartBeat': '心跳声',
    'audio.Astral': '星界',
    'audio.Fountain': '喷泉',
    'audio.Train':'火车',
    'audio.AsmrFoam':'泡沫',
    'audio.Tribal':'部落',
    'audio.India':'印度',
    'audio.UrbanRain':'都市之雨',
    'audio.Cavern':'洞穴',
    'audio.Reactor':'反应堆',
    'audio.WindChimes':'风铃',
    'audio.Spaceship':'宇宙飞船',
    'audio.AsmrMakeupBrush':'化妆刷',
    'audio.Sailing':'航行',
    'audio.Voices':'声音',
    'audio.Watching':'观看',
    'audio.BassMusic':'低音音乐',
    'audio.SpokenSleepAffirmations':'睡眠肯定',
    'audio.ColdRattle':'空调声',
    'audio.AsmrElvishWhispers':'精灵低语',
    'audio.Chirp':'唧唧声',
    'audio.Orbit':'轨道',
    'audio.Drum':'鼓',
    'audio.ServerRoom':'机房声',
    'audio.Storm':'暴雨',
    'audio.AsmrBoilingWater':'沸水',
    'audio.Flute2':'东方长笛',
    'audio.Choir':'合唱',
    'audio.Airplane':'飞机',
    'audio.Starfield':'星空',
    'audio.SunnyDay':'晴天',
    'audio.Guitar':'吉他',
    'audio.AsmrWriting':'写字',
    'audio.Dramatic':'戏剧性',
    'audio.Butterfly':'蝴蝶',
    'audio.Medieval':'中世纪',
    'audio.EarthDrama':'地球剧场',
    'audio.Dreams':'梦',
    'audio.AsmrIceCube':'冰块',
    'audio.WindSurge':'风潮',
    'audio.Forest':'森林',
    'audio.Abstract':'抽象',
    'audio.BabyShusher':'婴儿嘘声',
    'audio.GreenNoise':'绿噪音',
    'audio.MilkyWay':'银河系',
    'audio.Spring':'春天',
    'audio.AsmrFingerFlutter':'手指舞动',
    'audio.Toskana':'图斯卡纳',
    'audio.City':'城市',
    'audio.Sprinkler':'洒水器',
    'audio.SlowWaves':'慢波',
    'audio.LightRain':'细雨',
    'audio.AsmrSkillet':'煎锅音效',
    'audio.HeavyRain':'暴雨',
    'audio.RainyDay':'雨天',
    'audio.Underwater':'水下',
    'audio.TibetanBowlSmall':'小藏钵',
    'audio.TibetanBowlMedium':'中藏钵',
    'audio.TibetanBowlBig':'大藏钵',
    'audio.AsmrPurring':'咕噜',
    'audio.Immersed':'沉浸',
    'audio.Afternoon':'午后',
    'audio.Rainstorm':'暴风雨',
    'audio.ForestRain':'林中雨声',
    'audio.Whales':'鲸鱼',
    'audio.Seaside':'海边',
    'audio.IcySnow':'冰雪',
    'audio.CuckooBird':'杜鹃鸟',
    'audio.Aquarium':'水族馆',
    'audio.BambooWaterFountain':'竹泉',
    'audio.BathFilling':'浴缸加水',
    'audio.BoilingPotion':'沸腾之水',
    'audio.DrivingInRain':'雨中驾驶',
    'audio.FloatingBoat':'浮船',
    'audio.HotTub':'热水浴缸',
    'audio.RainOnWindow':'雨打窗前',
    'audio.WavesOnRocks':'浪冲礁石',
    'audio.Whales2':'鲸鱼之旅',
    'audio.Seagulls':'海鸥',
    'audio.RainOnRoof':'屋顶雨声',
    'audio.Duduk':'杜杜克笛',
    'audio.Playground':'运动场',
    'audio.AsmrRainDrops':'雨滴',
    'audio.Owls':'猫头鹰',
    'audio.Humming':'哼唱',
    'audio.GrandfatherClock':'老爷钟',
    'audio.Frogs':'蛙',
    'audio.Dryer':'烘干机',
    'audio.CatPurring':'猫叫',
    'audio.BaliMist':'巴厘之雾',
    'audio.Thunderstorm':'雷暴雨',
    'audio.CityAmbience':'城市气氛',
    'audio.IndianDrums':'印度鼓',
    'audio.PachelbelCanon':'帕赫贝尔卡农',
    'audio.Wolf':'狼',
    'audio.FogHorn':'雾角',
    'audio.Vacuum':'真空',
    'audio.Loon':'潜鸟',
    'audio.Keyboard':'键盘',
    'audio.MonkChant':'僧侣颂经',
    'audio.AsmrWalkingOnSnow':'雪中漫步',
    'audio.OscillatingFan':'摇头扇',
    'audio.Womb':'子宫声波',
    'audio.BabyMarimba':'宝贝马林巴音效',
    'audio.SpokenHypnoticWords':'催眠字词',
    'audio.BabyBells':'宝贝铃铛',
    'audio.SingingBowlSmall':'小颂钵',
    'audio.SingingBowlMedium':'中颂钵',
    'audio.SingingBowlBig':'大颂钵',
    'audio.Jupiter':'木星',
    'audio.Cicadas':'蝉',
    'audio.WindInTrees':'林中风',
    'audio.Peepers':'雨蛙',
    'audio.RustlingLeaves':'叶子沙沙',
    'audio.Crowd':'人群',
    'audio.RainOnTent':'帐篷雨声',
    'audio.TibetanBowls':'西藏钵',
    'audio.BrahmsLullaby':'勃拉姆斯摇篮曲',
    'audio.SpokenCountingSheep':'数羊',
    'audio.Joy':'欢乐',
    'audio.Rattle':'拨浪鼓音效',
    'audio.LappingWater':'拍水声',
    'audio.DistantTrain':'远处火车',
    'audio.MagicChimes':'魔法编钟',
    'audio.Carnival':'狂欢节',
    'audio.TruckEngine':'卡车引擎',
    'audio.SweetDreams':'甜蜜的梦',
    'audio.HairDryer':'吹风机',
    'audio.SweetHourPrayer':'甜蜜祈祷',
    'audio.Ancestral':'祖传',
    'audio.FireCrackles':'篝火爆裂声',
    'audio.Highway':'高速公路',
    'audio.Om':'奥姆',
    'audio.Harmony':'和谐',
    'audio.Binaural2.5hz':'2.5HZ-无梦睡眠（配戴耳机）',
    'audio.Binaural4hz':'4HZ-梦（配戴耳机）',
    'audio.Binaural5hz':'5HZ-深度冥想（配戴耳机）',
    'audio.Binaural8hz':'8HZ-睡前（配戴耳机）',
    'audio.Binaural10hz':'10HZ-放松（配戴耳机）',
    'audio.Binaural20hz':'20HZ-集中（配戴耳机）',
    'audio.Isochronic2.5hz':'2.5HZ-无梦睡眠',
    'audio.Isochronic4hz':'4HZ-梦',
    'audio.Isochronic5hz':'5HZ-深度冥想',
    'audio.Isochronic8hz':'8HZ-睡前',
    'audio.Isochronic10hz':'10HZ-放松',
    'audio.Isochronic20hz':'20HZ-集中',
    'audio.Solfeggio174hz':'174HZ-治愈波动',
    'audio.Solfeggio285hz':'285HZ-回春',
    'audio.Solfeggio396hz':'396HZ-焦虑治疗师',
    'audio.Solfeggio417hz':'417HZ-能力净化',
    'audio.Solfeggio432hz':'432HZ-积极的振动',
    'audio.Solfeggio528hz':'582HZ-情绪释放',
    'audio.SingingBowl':'颂钵',
} as any